name: Push

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependecies
        run: |
          python3 -m pip install --upgrade pip

  deploy:
    name: run_aws_command
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependecies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install awscli --upgrade --user
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: <region>
          role-to-assume: arn:aws:iam::<account_number>:role/<role_name>
      
      - name: Deploy
        run: |
          aws s3 ls 

